/**
 * Parse resource file generated by ResDepot
 *
 * Created by malloyzhu on 2015/5/18.
 *
 * Usage:
 * Editing resouce groups configuration in ResDepot, then find the
 * group by [resGroup.groupName] in code.
 *
 * Caution:
 * Scene, Node, Plist, Tmx/Png...file should be included in preload before
 * starting a new scene.
 *
 * More details please visit: http://www.egret-labs.org/resdepot
 *
 */

var res;
var resGroup;
var resList;
var resPath = "res/";

function loadResources() {
    var configFile = cc.path.join(resPath, "resource.json");
    var config = JSON.parse(Util.readTxtFileSync(configFile));

    res = res || {};
    var resources = config.resources;
    for (var i in resources) {
        var name = resources[i].name;
        var url = resources[i].url;
        res[name] = resPath + url;
    }

    resList = resList || [];
    resGroup = resGroup || {};
    var groups = config.groups;
    for (var i in groups) {
        var name = groups[i].name;
        var group = [];
        var keysArr = groups[i].keys.split(",");
        for (var j in keysArr) {
            var value = res[keysArr[j]];
            group.push(value);
            resList.push(value);
        }
        resGroup[name] = group;
    }
};

loadResources();
